// <auto-generated />
using Book.Servies.BookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book.Servies.BookAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240303102013_mg1")]
    partial class mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Book.Servies.BookAPI.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tblBook");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            ISBN = "978-0743273565",
                            PublishedYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            ISBN = "978-0061120084",
                            PublishedYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            ISBN = "978-0451524935",
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            ISBN = "978-1503290564",
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.K. Rowling",
                            ISBN = "978-0590353427",
                            PublishedYear = 1997,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.D. Salinger",
                            ISBN = "978-0316769488",
                            PublishedYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Harper Lee",
                            ISBN = "978-0061120084",
                            PublishedYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            ISBN = "978-0547928227",
                            PublishedYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.R.R. Tolkien",
                            ISBN = "978-0544003415",
                            PublishedYear = 1954,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Herman Melville",
                            ISBN = "978-1503280787",
                            PublishedYear = 1851,
                            Title = "Moby-Dick"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
